In [1]:
import numpy as np 
from numpy import genfromtxt

In [2]:
data = genfromtxt("../DATA/bank_note_data.txt",delimiter=",")

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
len(data)

1372

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
len(X_train)

919

In [13]:
len(X_test)

453

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_object = MinMaxScaler()

In [16]:
scaler_object.fit(X_train)
#what this fit does is it basically just finds the minimum value and the maximum value
#why we just fit X_train
#That is because we want to make sure that this scalar object doesn't get to peek at any test data.

MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
scaled_x_train = scaler_object.transform(X_train)

In [18]:
scaled_x_test = scaler_object.transform(X_test)

In [19]:
scaled_x_train.max()
#the range after scaling is between 1 , 0

1.0000000000000002

In [20]:
scaled_x_train.min()

0.0

In [21]:
from keras.models import Sequential
# allows you to create models layer-by-layer for most problems
from keras.layers import Dense
# the layer that contains all the neurons that are deeply connected within themselves
# Keras is a high-level neural network library that runs on top of TensorFlow.

Using TensorFlow backend.


In [22]:
model = Sequential()
#first layer
model.add(Dense(4,input_dim=4,activation="relu"))
#4 is num of neurons
#hidden layer
model.add(Dense(8,activation="relu"))
#last layer
model.add(Dense(1,activation="sigmoid"))

In [23]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [24]:
model.fit(scaled_x_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 6s - loss: 0.6876 - acc: 0.6344
Epoch 2/50
 - 0s - loss: 0.6832 - acc: 0.6768
Epoch 3/50
 - 0s - loss: 0.6775 - acc: 0.6888
Epoch 4/50
 - 0s - loss: 0.6702 - acc: 0.6975
Epoch 5/50
 - 0s - loss: 0.6602 - acc: 0.6812
Epoch 6/50
 - 0s - loss: 0.6477 - acc: 0.6921
Epoch 7/50
 - 0s - loss: 0.6350 - acc: 0.6964
Epoch 8/50
 - 0s - loss: 0.6226 - acc: 0.7018
Epoch 9/50
 - 0s - loss: 0.6098 - acc: 0.7051
Epoch 10/50
 - 0s - loss: 0.5973 - acc: 0.7084
Epoch 11/50
 - 0s - loss: 0.5845 - acc: 0.7193
Epoch 12/50
 - 0s - loss: 0.5722 - acc: 0.7214
Epoch 13/50
 - 0s - loss: 0.5564 - acc: 0.7432
Epoch 14/50
 - 0s - loss: 0.5289 - acc: 0.7563
Epoch 15/50
 - 0s - loss: 0.5028 - acc: 0.7715
Epoch 16/50
 - 0s - loss: 0.4775 - acc: 0.7867
Epoch 17/50
 - 0s - loss: 0.4531 - acc: 0.8009
Epoch 18/50
 - 0s - loss: 0.4294 - acc: 0.8259
Epoch 19/50
 - 0s - loss: 0.4058 - acc: 0.8487
Epoch 20/50
 - 0s - loss: 0.3847 - acc: 0.8716
Epoch 21/50
 - 0s - loss: 0.3644 - acc: 0.8792
Epoch 22/50
 - 0s - lo

In [26]:
#model.predict_classes(scaled_x_test)
#now we evaluate our model and fit our test set

In [28]:
model.metrics_names

['loss', 'acc']

In [29]:
from sklearn.metrics import confusion_matrix , classification_report

In [30]:
predictions = model.predict_classes(scaled_x_test)

In [32]:
confusion_matrix(y_test,predictions)

array([[255,   2],
       [ 10, 186]], dtype=int64)

In [33]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.96      0.99      0.98       257
        1.0       0.99      0.95      0.97       196

avg / total       0.97      0.97      0.97       453



In [34]:
model.save("mysupermodel.h5")

In [35]:
from keras.models import load_model

In [36]:
newmodel = load_model("mysupermodel.h5")